namespace Events
{
	public enum EventId
	{
		ApplicationExit,
		NetPlayerDisconnected,
		NetPlayerConnected,
		NetPlayerIdentified,
		PlayerAimed,
        PlayerKilled,
        DebugUiActivated,
		EntitySpawned,
		EntityDestroyed,
		EntityHealthUpdate,
		EntityMoved,
		EntityFired,
		EntityFiredLocal,
		EntityTransformUpdated,
        GameStartTriggered,
        HidePromptText,
        ShowPromptText,
        ShowTriggerPrompt,
        VRControllerPulse,
		VRControllerTriggerPress,
		VRControllerTriggerRelease,
		VRControllerTouchpadPress,
		VRControllerTouchpadDrag,
		VRControllerTouchpadRelease,
		DebugCameraControlsActive
	}
}
